# Generated by Django 6.0.7 on 2026-07-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='프로필 사진'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upfile',
            field=models.FileField(blank=True, null=True, upload_to='upfile/%Y%M%/%d', verbose_name='업로드 파일'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='생일'),
        ),
    ]
